name: Deploy custom webApp on yunohost

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Push files via SFTP
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_PORT: ${{ secrets.SFTP_PORT }}
        SFTP_USER: ${{ secrets.SFTP_USER }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        lftp -u "$SFTP_USER","$SFTP_PASSWORD" "$SFTP_HOST" <<EOF
        mirror -R ./ /path/to/remote/directory/
        bye
        EOF